// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Orders.Data;

#nullable disable

namespace Orders.Data.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260928140036_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Orders.Data.Entities.InboxMessage", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("EventId");

                    b.ToTable("inbox_messages", (string)null);
                });

            modelBuilder.Entity("Orders.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("customer_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_orders_status", "\"status\" IN ('Pending', 'Reserving', 'Charging', 'Confirmed', 'Cancelled')");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 28, 10, 0, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUSTOMER-001",
                            Status = "Pending",
                            TotalAmount = 39.98m,
                            UpdatedAt = new DateTime(2026, 9, 28, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 9, 28, 10, 1, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUSTOMER-002",
                            Status = "Reserving",
                            TotalAmount = 59.97m,
                            UpdatedAt = new DateTime(2026, 9, 28, 10, 1, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 9, 28, 10, 2, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUSTOMER-003",
                            Status = "Charging",
                            TotalAmount = 69.97m,
                            UpdatedAt = new DateTime(2026, 9, 28, 10, 2, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 9, 28, 10, 3, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUSTOMER-004",
                            Status = "Confirmed",
                            TotalAmount = 89.98m,
                            UpdatedAt = new DateTime(2026, 9, 28, 10, 3, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 9, 28, 10, 4, 0, 0, DateTimeKind.Utc),
                            CustomerId = "CUSTOMER-005",
                            Status = "Cancelled",
                            TotalAmount = 49.99m,
                            UpdatedAt = new DateTime(2026, 9, 28, 10, 4, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Orders.Data.Entities.OrderLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sku");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("order_lines", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            OrderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Quantity = 2,
                            Sku = "WIDGET-01",
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = 2L,
                            OrderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Quantity = 2,
                            Sku = "WIDGET-02",
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 3L,
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Quantity = 2,
                            Sku = "WIDGET-03",
                            UnitPrice = 34.99m
                        },
                        new
                        {
                            Id = 4L,
                            OrderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Quantity = 2,
                            Sku = "WIDGET-04",
                            UnitPrice = 44.99m
                        },
                        new
                        {
                            Id = 5L,
                            OrderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Quantity = 1,
                            Sku = "WIDGET-01",
                            UnitPrice = 49.99m
                        });
                });

            modelBuilder.Entity("Orders.Data.Entities.OrderSagaState", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid?>("LastProcessedEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_processed_event_id");

                    b.Property<bool>("PaymentCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("payment_completed");

                    b.Property<bool>("ReservationCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("reservation_completed");

                    b.HasKey("OrderId");

                    b.ToTable("order_saga_state", (string)null);

                    b.HasData(
                        new
                        {
                            OrderId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PaymentCompleted = false,
                            ReservationCompleted = false
                        },
                        new
                        {
                            OrderId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PaymentCompleted = false,
                            ReservationCompleted = false
                        },
                        new
                        {
                            OrderId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PaymentCompleted = false,
                            ReservationCompleted = true
                        },
                        new
                        {
                            OrderId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PaymentCompleted = true,
                            ReservationCompleted = true
                        },
                        new
                        {
                            OrderId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PaymentCompleted = false,
                            ReservationCompleted = true
                        });
                });

            modelBuilder.Entity("Orders.Data.Entities.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Orders.Data.Entities.OrderLine", b =>
                {
                    b.HasOne("Orders.Data.Entities.Order", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Orders.Data.Entities.OrderSagaState", b =>
                {
                    b.HasOne("Orders.Data.Entities.Order", "Order")
                        .WithOne("SagaState")
                        .HasForeignKey("Orders.Data.Entities.OrderSagaState", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Orders.Data.Entities.Order", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("SagaState")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
